xnw_zong_ping:
    resource: "@XNWZongPingBundle/Resources/config/routing.xml"
    prefix:   /

xnw_zong_ping2:
    resource: "@XNWZongPingBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
